from enum import Enum

class UserRole(Enum):
    USER = "USER"
    INSTRUCTOR = "INSTRUCTOR"
    ADMIN = "ADMIN"

class ChapterLevel(Enum):
    FOUNDATION = "FOUNDATION"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"

class TopicArea(Enum):
    EMBODIED_INTELLIGENCE = "EMBODIED_INTELLIGENCE"
    SIMULATION = "SIMULATION"
    CONTROL_SYSTEMS = "CONTROL_SYSTEMS"
    VISION_LANGUAGE_ACTION = "VISION_LANGUAGE_ACTION"